basePath: /
definitions:
  handler.CreateRequestInput:
    properties:
      description:
        type: string
      threat_type_id:
        type: integer
      title:
        type: string
    required:
    - description
    - threat_type_id
    - title
    type: object
  handler.LoginAPIInput:
    properties:
      email:
        type: string
      password:
        type: string
      user_type:
        enum:
        - employee
        - specialist
        type: string
    required:
    - email
    - password
    - user_type
    type: object
  handler.RegisterAPIInput:
    properties:
      email:
        type: string
      full_name:
        type: string
      password:
        type: string
      phone:
        type: string
      user_type:
        type: string
    required:
    - email
    - full_name
    - password
    - phone
    - user_type
    type: object
host: localhost:8080
info:
  contact:
    email: maksim.ago@mail.ru
    name: API Support
    url: https://vk.com/club234398304
  description: API для мониторинга угроз безопасности в информационных системах. Позволяет
    регистрировать и отслеживать инциденты, связанные с безопасностью, а также управлять
    ими.
  license:
    name: AS IS (NO WARRANTY)
  title: Threat Monitoring
  version: "1.0"
paths:
  /api/auth/login:
    post:
      consumes:
      - application/json
      description: Позволяет зайти за пользователя, используя его данные.
      parameters:
      - description: Данные для входа
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handler.LoginAPIInput'
      produces:
      - application/json
      responses:
        "200":
          description: Успешный вход
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Неверные данные
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Неверный email или пароль
          schema:
            additionalProperties: true
            type: object
        "403":
          description: Неверный тип пользователя
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Ошибка сервера
          schema:
            additionalProperties: true
            type: object
      summary: Зайти за пользователя
      tags:
      - auth
  /api/auth/logout:
    post:
      consumes:
      - application/json
      description: Завершает текущую авторизованную сессию.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
      security:
      - ApiKeyAuth: []
      summary: Выход из системы
      tags:
      - auth
  /api/auth/register:
    post:
      consumes:
      - application/json
      description: Позволяет зарегистрировать пользователя. Необходим вход за специалиста.
      parameters:
      - description: Данные для регистрации
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handler.RegisterAPIInput'
      produces:
      - application/json
      responses:
        "200":
          description: Успешная регистрация
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Неверные данные
          schema:
            additionalProperties: true
            type: object
        "403":
          description: Неверный тип пользователя
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Ошибка сервера
          schema:
            additionalProperties: true
            type: object
      security:
      - ApiKeyAuth: []
      summary: Зарегистрировать пользователя
      tags:
      - auth
  /api/requests:
    get:
      consumes:
      - application/json
      description: Возвращает список заявок. Доступно только после авторизации.
      parameters:
      - description: Статус заявки
        in: query
        name: status
        type: string
      - description: Дата от (YYYY-MM-DD)
        in: query
        name: date_from
        type: string
      - description: Дата до (YYYY-MM-DD)
        in: query
        name: date_to
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Ошибка с параметрами запроса
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Требуется авторизация
          schema:
            additionalProperties: true
            type: object
        "403":
          description: Доступ запрещён
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Внутренняя ошибка сервера
          schema:
            additionalProperties: true
            type: object
      security:
      - ApiKeyAuth: []
      summary: Получить список заявок
      tags:
      - requests
    post:
      consumes:
      - application/json
      description: Создает новую заявку для авторизованного пользователя.
      parameters:
      - description: Данные заявки
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handler.CreateRequestInput'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Ошибка при создании заявки
          schema:
            additionalProperties: true
            type: object
      security:
      - ApiKeyAuth: []
      summary: Создать заявку
      tags:
      - requests
  /api/requests/{id}:
    delete:
      consumes:
      - application/json
      description: Удаляет заявку, если у пользователя есть право на это.
      parameters:
      - description: ID заявки
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
        "403":
          description: Forbidden
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties: true
            type: object
      security:
      - ApiKeyAuth: []
      summary: Удалить заявку
      tags:
      - requests
    get:
      consumes:
      - application/json
      description: Возвращает заявку по ID. Доступно только после авторизации.
      parameters:
      - description: ID заявки
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Неверный ID заявки
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Требуется авторизация
          schema:
            additionalProperties: true
            type: object
        "403":
          description: Доступ запрещён
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Заявка не найдена
          schema:
            additionalProperties: true
            type: object
      security:
      - ApiKeyAuth: []
      summary: Получить заявку
      tags:
      - requests
    put:
      consumes:
      - application/json
      description: Обновляет существующую заявку, если пользователь является её создателем.
      parameters:
      - description: ID заявки
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
        "403":
          description: Forbidden
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties: true
            type: object
      security:
      - ApiKeyAuth: []
      summary: Обновить заявку
      tags:
      - requests
  /api/requests/{id}/complete:
    put:
      consumes:
      - application/json
      description: Специалист завершает заявку со статусом closed или rejected.
      parameters:
      - description: ID заявки
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
        "403":
          description: Forbidden
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties: true
            type: object
      security:
      - ApiKeyAuth: []
      summary: Завершить заявку
      tags:
      - requests
  /api/requests/{id}/facts:
    get:
      consumes:
      - application/json
      description: Возвращает список фактов для заявки. Требуется авторизация.
      parameters:
      - description: ID заявки
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties: true
            type: object
      security:
      - ApiKeyAuth: []
      summary: Получить факты заявки
      tags:
      - requests
    post:
      consumes:
      - application/json
      description: Создает новый факт для заявки. Требуется авторизация сотрудника.
      parameters:
      - description: ID заявки
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
        "403":
          description: Forbidden
          schema:
            additionalProperties: true
            type: object
      security:
      - ApiKeyAuth: []
      summary: Добавить факт к заявке
      tags:
      - requests
  /api/requests/{id}/submit:
    put:
      consumes:
      - application/json
      description: Специалист принимает заявку для обработки.
      parameters:
      - description: ID заявки
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
        "403":
          description: Forbidden
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties: true
            type: object
      security:
      - ApiKeyAuth: []
      summary: Взять заявку в работу
      tags:
      - requests
schemes:
- http
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
